"""
Payment Recovery Engine — operations console.

Run from the repository root with:

    python -m streamlit run dashboard/app.py

`-m`, and from the root, because `streamlit run` puts the *script's* directory
on sys.path (web/bootstrap.py) — not the working directory — so a bare
`streamlit run dashboard/app.py` cannot import the `dashboard` package the
lines below need. run.sh and docker-compose.yml both use the `-m` form.

Password-gated: this renders live payment data next to a service published
through a public tunnel, and Streamlit binds a port like any other server. The
gate is the first thing that runs after set_page_config, so no query reaches
the database until it passes.

The sub-pages live in dashboard/views/, NOT dashboard/pages/. Streamlit
auto-registers every module under a directory literally named `pages/` as its
own routable URL, which would have handed out /bank_breakdown and friends with
this gate bypassed entirely — and served them broken, since each is a render()
function with no top-level body to execute.
"""

from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="Recovery Engine",
    page_icon="₹",
    layout="wide",
    initial_sidebar_state="expanded",
)

from dashboard import theme  # noqa: E402
from dashboard.auth import (  # noqa: E402
    dashboard_password,
    password_is_correct,
)

theme.apply()


# ── Auth ─────────────────────────────────────────────────────────────────
def require_password() -> None:
    """
    Render the sign-in form and stop the script unless already authenticated.

    st.stop() rather than an early return: this module is a script, and every
    caller of every helper below it is at module scope. Stopping is the only
    way to guarantee nothing further executes.
    """
    if st.session_state.get("authenticated"):
        return

    st.markdown(
        f"""
        <div style="max-width:400px;margin:14vh auto 1.6rem auto;">
          <div style="font-family:{theme.FONT_MONO};color:{theme.BRASS_TEXT};
                      font-size:0.78rem;letter-spacing:0.14em;margin-bottom:0.5rem;">
            PAYMENT RECOVERY ENGINE
          </div>
          <h1 style="margin:0 0 0.5rem 0;font-size:2rem;">Sign in</h1>
          <p style="color:{theme.SLATE};font-size:0.9rem;margin:0;">
            This console reads live payment data.
          </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if not dashboard_password():
        st.error(
            "DASHBOARD_PASSWORD is not set, so this console cannot be unlocked. "
            "Set it in .env and restart — `./run.sh` generates one for you."
        )
        st.stop()

    _, mid, _ = st.columns([1, 1.4, 1])
    with mid, st.form("login"):
        # Visible label + helper text: a password hint belongs beside the
        # field, not as placeholder-only text that vanishes on focus.
        st.markdown(
            "Password",
            help="Generated by run.sh into .env on first launch.",
        )
        supplied = st.text_input(
            "Password", type="password", label_visibility="collapsed"
        )
        submitted = st.form_submit_button("Sign in", width="stretch")
    if submitted:
        if password_is_correct(supplied):
            # The password itself is never kept — only the fact that it matched.
            st.session_state["authenticated"] = True
            st.rerun()
        else:
            st.error("Incorrect password")
    st.stop()


require_password()


# ── DB ───────────────────────────────────────────────────────────────────
from dashboard.db import get_db_engine, no_data, query_db  # noqa: E402

OVERVIEW_SQL = """
SELECT
  (SELECT COUNT(*) FROM payment_failures)                             AS failures,
  (SELECT COUNT(*) FROM recovery_cases)                               AS cases,
  (SELECT COUNT(*) FROM recovery_cases WHERE state = 'recovered')     AS recovered_cases,
  (SELECT COUNT(*) FROM retry_attempts WHERE result = 'pending')      AS pending,
  (SELECT COUNT(*) FROM retry_attempts WHERE result = 'scheduled')    AS scheduled,
  (SELECT COALESCE(SUM(amount_at_risk), 0)   FROM recovery_cases)     AS at_risk_paise,
  (SELECT COALESCE(SUM(amount_recovered), 0) FROM recovery_cases)     AS recovered_paise,
  (SELECT COALESCE(SUM(amount_recovered), 0) FROM recovery_cases
     WHERE recovered_via_attempt_id IS NOT NULL)                      AS attributed_paise
"""


def _sync_deep_link() -> None:
    """Keep ?view= in the URL so any console state is a shareable URL."""
    chosen = st.session_state.get("nav", _LABELS[0])
    slug = next(slug for label, slug in _SECTIONS if label == chosen)
    if st.query_params.get("view") != slug:
        st.query_params["view"] = slug


_SECTIONS = [
    ("Overview", "overview"),
    ("Recovery funnel", "recovery-funnel"),
    ("Banks & rails", "banks-rails"),
    ("Policy eval", "policy-eval"),
    ("Cases & audit", "cases-audit"),
    ("Operations", "operations"),
]
_LABELS = [label for label, _ in _SECTIONS]


# ── Sidebar ──────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown(
        f"""
        <div style="display:flex;align-items:center;gap:0.7rem;
                    margin:0.1rem 0 0.25rem 0.15rem;">
          <div style="width:34px;height:34px;border-radius:9px;flex:none;
                      background:linear-gradient(145deg,#B8900F,{theme.BRASS});
                      box-shadow:inset 0 1px 0 rgba(255,255,255,0.28),
                                 0 6px 18px rgba(165,129,8,0.30);
                      display:flex;align-items:center;justify-content:center;">
            <span style="font-family:{theme.FONT_DISPLAY};font-weight:800;
                         font-size:1.05rem;color:#171204;">₹</span>
          </div>
          <div>
            <div style="font-family:{theme.FONT_DISPLAY};font-weight:800;font-size:1.02rem;
                        letter-spacing:-0.02em;color:{theme.PAPER};line-height:1.05;">
              Recovery Engine
            </div>
            <div style="color:{theme.SLATE};font-size:0.7rem;margin-top:0.12rem;">
              Payment failure recovery
            </div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.markdown(
        f"<div style='height:1px;background:{theme.LINE};margin:"
        f"1rem 0 0.4rem 0;'></div>",
        unsafe_allow_html=True,
    )

    incoming = st.query_params.get("view", "overview")
    default_idx = next(
        (i for i, (_, slug) in enumerate(_SECTIONS) if slug == incoming), 0
    )
    if "nav" not in st.session_state:
        st.session_state["nav"] = _LABELS[default_idx]

    page = st.radio(
        "Section",
        _LABELS,
        key="nav",
        label_visibility="collapsed",
        captions=[
            "Money at risk, and what came back",
            "Where the pipeline leaks",
            "Measured routing quality",
            "Does the agent beat the baseline",
            "Lifecycle and audit trail of every case",
            "Scheduler, guardrail vetoes, ledger health",
        ],
        on_change=_sync_deep_link,
    )
    # Canonical URL sync, BOTH directions, every render: deep-link in reflects
    # its slug back out, and nav clicks update the param here rather than
    # trusting on_change (Streamlit swallows param writes from callbacks on
    # bound widgets — the post-render write below is the reliable path).
    current_slug = next(slug for label, slug in _SECTIONS if label == page)
    if st.query_params.get("view") != current_slug:
        st.query_params["view"] = current_slug

    st.divider()

    # Live connection chip. A console that cannot say whether it is looking at
    # real data is a console that shows stale numbers with total confidence.
    connected = get_db_engine() is not None
    dot = theme.TEAL if connected else theme.CLAY_TEXT
    pulse = " rc-pulse" if connected else ""
    st.markdown(theme.chip(
        ("database connected" if connected else "database unreachable"),
        tone="teal" if connected else "clay",
    ).replace(
        "<span", f"<span class='{pulse.strip()}' style='width:7px;height:7px;"
        f"border-radius:50%;background:{dot};display:inline-block;"
        f"margin-right:0.2rem;'></span><span", 1
    ), unsafe_allow_html=True)

    # Data caches live for 30s; this button is how an operator forces now.
    if st.button("Refresh data", width="stretch"):
        st.cache_data.clear()
        st.rerun()

    # Live mode: KPI panels rerun themselves every 30s via st.fragment — only
    # that panel rerenders, not the page. Off by default: an unwatched console
    # polling a production database forever is not free.
    st.toggle("Live · refresh 30s", key="live_mode", value=False)


# ── Overview ─────────────────────────────────────────────────────────────
if page == "Overview":
    theme.page_header("OVERVIEW", "Money at risk, and what came back")

    live = bool(st.session_state.get("live_mode"))

    @st.fragment(run_every="30s" if live else None)
    def _money_panel() -> None:
        row = query_db(OVERVIEW_SQL)
        if row is None or row.empty:
            no_data("recovery activity")
            return
        cases = int(row["cases"].iloc[0])
        recovered_cases = int(row["recovered_cases"].iloc[0])
        at_risk = int(row["at_risk_paise"].iloc[0])
        recovered = int(row["recovered_paise"].iloc[0])
        attributed = int(row["attributed_paise"].iloc[0])
        pending = int(row["pending"].iloc[0])
        scheduled = int(row["scheduled"].iloc[0])

        st.markdown(
            theme.ledger_band(at_risk, recovered, attributed),
            unsafe_allow_html=True,
        )

        c1, c2, c3, c4 = st.columns(4)
        with c1:
            theme.tile(
                "Money attributed", theme.compact_inr(attributed),
                icon="money", tone="brass",
                foot="earned by links we sent",
                help="Recovered through a payment link this engine sent. Money "
                     "the customer paid on their own is excluded — real "
                     "revenue, but not our result.",
            )
        with c2:
            rate = (recovered_cases / cases * 100) if cases else 0.0
            st.markdown(
                f"""
                <div class="rc-tile">
                  <div style="display:flex;justify-content:space-between;
                              align-items:center;margin-bottom:0.45rem;">
                    <span style="color:{theme.SLATE};text-transform:uppercase;
                                 letter-spacing:0.07em;font-size:0.68rem;
                                 font-weight:500;">Recovery rate</span>
                    <span style='width:26px;height:26px;border-radius:8px;
                                 display:inline-flex;align-items:center;
                                 justify-content:center;
                                 background:rgba(165,129,8,0.10);
                                 border:1px solid rgba(165,129,8,0.25);
                                 color:{theme.BRASS_TEXT};'
                          title='Cases closed recovered, over cases opened'>
                      {theme.icon('trend-up', size=15)}</span>
                  </div>
                  <div style="display:flex;align-items:center;gap:0.9rem;">
                    {theme.ring(rate, label='Recovery rate')}
                    <span style="color:{theme.SLATE};font-size:0.74rem;
                                 line-height:1.4;">
                      {recovered_cases:,} of {cases:,}<br>cases closed
                      recovered</span>
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with c3:
            theme.tile(
                "In flight", f"{pending:,}", icon="pending",
                tone="clay" if pending > 20 else "paper",
                foot="write-ahead, awaiting outcome",
                help="Attempts written ahead of the Razorpay call, not yet "
                     "resolved.",
            )
        with c4:
            theme.tile(
                "Scheduled", f"{scheduled:,}", icon="clock",
                foot="fire from the Layer 6 scheduler" if scheduled
                     else "nothing waiting",
                help="Deferred retry_at decisions parked until their moment "
                     "arrives.",
            )

    _money_panel()

    st.divider()
    theme.section(
        "Recent decisions",
        "Newest first. Every row is one agent decision and its outcome.",
    )

    recent = query_db("""
        SELECT ra.created_at AS "When", ra.payment_id AS "Payment",
               ra.action_type AS "Action", ra.result AS "Result",
               ra.agent_type AS "Decided by", ra.channel AS "Channel",
               ra.guardrail_passed AS "Guardrail", ra.scheduled_at AS "Fires at"
        FROM retry_attempts ra ORDER BY ra.created_at DESC LIMIT 12
    """)
    if recent is not None and len(recent) > 0:
        export_col, list_col = st.columns([1.6, 8.4])
        with export_col:
            st.download_button(
                "Export CSV",
                recent.to_csv(index=False).encode("utf-8"),
                file_name="recent_decisions.csv",
                mime="text/csv",
            )
        rows = []
        for _, r in recent.iterrows():
            guard = (
                f"<span style='color:{theme.TEAL_TEXT};display:inline-flex;"
                f"align-items:center;gap:0.25rem;font-size:0.76rem;' "
                f"title='guardrail passed'>{theme.icon('check', size=13)}pass</span>"
                if bool(r["Guardrail"])
                else (
                    "<span style='color:" + theme.CLAY_TEXT +
                    ";display:inline-flex;align-items:center;gap:0.25rem;"
                    "font-size:0.76rem;' title='guardrail vetoed'>"
                    + theme.icon("cross", size=13) + "veto</span>"
                )
            )
            fires = theme.fmt_ist(r["Fires at"]) if r["Fires at"] is not None else ""
            fires_html = (
                f"<span style='color:{theme.SLATE};font-size:0.74rem;'>→ {fires}</span>"
                if fires != "—"
                else ""
            )
            rows.append(f"""
              <div class="rc-row" style="display:grid;
                          grid-template-columns:9rem 1fr 8rem 7rem 6.5rem;
                          gap:0.8rem;align-items:center;
                          padding:0.55rem 0.35rem;
                          border-bottom:1px solid {theme.LINE};">
                <span style="font-family:{theme.FONT_MONO};color:{theme.SLATE};
                             font-size:0.76rem;">{theme.fmt_ist(r['When'])}</span>
                <span style="font-family:{theme.FONT_MONO};color:{theme.PAPER};
                             font-size:0.8rem;">{r['Payment']}
                    {fires_html}</span>
                <span>{theme.status_chip(r['Action'])}</span>
                <span>{theme.status_chip(r['Result'] or 'pending')}</span>
                <span style="text-align:right;">{guard}
                  <span style="color:{theme.MUTE};font-size:0.7rem;
                               margin-left:0.4rem;" title="who decided">
                    {r['Decided by']}</span></span>
              </div>""")
        st.markdown(
            "<div style='overflow-x:auto;'><div style='min-width:760px;"
            "border-top:1px solid " + theme.LINE + ";'>" + "".join(rows)
            + "</div></div>",
            unsafe_allow_html=True,
        )
    else:
        # Deliberately not a demo table. Fabricated rows would be
        # indistinguishable from live output, and that is precisely what made
        # this console untrustworthy.
        st.info("No decisions recorded yet. Send traffic through the webhook endpoint.")

elif page == "Recovery funnel":
    from dashboard.views import recovery_funnel
    recovery_funnel.render()
elif page == "Banks & rails":
    from dashboard.views import bank_breakdown
    bank_breakdown.render()
elif page == "Policy eval":
    from dashboard.views import eval_results
    eval_results.render()
elif page == "Cases & audit":
    from dashboard.views import cases_audit
    cases_audit.render()
elif page == "Operations":
    from dashboard.views import operations
    operations.render()
